AZURE_RESOURCE = 'https://management.azure.com'.freeze
DEFAULT_ADDRESS_PREFIXES = ['10.2.0.0/16'].freeze
SUBNET = 'Subnet'.freeze
PUBLIC_IP = 'Public-IP-Address'.freeze
NETWORK_SECURITY_GROUP = 'Network-Security-Group'.freeze
STANDARD_STORAGE = 'Standard'.freeze
PREMIUM_STORAGE = 'Premium'.freeze
ALLOWED_STANDARD_REPLICATION = %w(LRS ZRS GRS RAGRS).freeze
API_VERSION = '2016-06-01'.freeze
RESOURCE_GROUP_NAME = 4.freeze
RESOURCE_PROVIDER_NAMESPACE = 6.freeze
RESOURCE_TYPE = 7.freeze
RESOURCE_NAME = 8.freeze
FAULT_DOMAIN_COUNT = 3.freeze
UPDATE_DOMAIN_COUNT = 5.freeze